### PR TITLE
Hotel 12

### PR DESCRIPTION
**Pull request by dudarenko-dmitry**
Hi, Mark.
Task is not ready yet.
I've just: 
1. transfered project to  Maven;
2. added loggers dependencies;
3. inject logger to HotelFacilities' classes and some other classes.

I need your help: my logger  writes only level.INFO but not DEBUG. And also log.file wasn't created.
I don't see mistakes. Could advise where can be problems? In dependencies? In .xml?

### CODE REVIEW

**Comment by Mark005** [comment]
you have two ways to do it the first is to set the debug level in the application and adjust it manually with a code or add  log4j.xml file

**Comment by dudarenko-dmitry** [comment]
Mark, Please check PR.

**Review by Mark005 — CHANGES_REQUESTED** [review]
good job, but you forgot to do one thing
image
please separate it to the 3 modules: UI, DI and core with your application

**Review by Mark005 — APPROVED** [review]
good job

**Pull request merged**
