### PR TITLE
Task 3.2 is done

### PR DESCRIPTION
**Pull request by dudarenko-dmitry**

### CODE REVIEW

**Review by mrseneca — COMMENTED** [review]
Very good, but need some fixes. Right now there no OOP at all in your code.
Let's create interface Flower and classes which will be implementing it. 
And also lets make bouquet separate class, which have collection of flowers as class attribute and can calculate cost itself

That will simplify your classes and also allow you easier read and support your code

**Comment by dudarenko-dmitry** [comment]
Hi. Alex.
May be better create abstract class Flower (not interface) and then create several classes (for ex. Rose, Tulip, etc.) which extend Flower?

**Comment by dudarenko-dmitry** [comment]
Please, check new variant TASK 3.2

**Review by mrseneca — APPROVED** [review]
Good work, good suggestion about abstract classes.
Now you read and understand code a lot easier

**Pull request merged**
